---
address: localhost
rackup: /var/www/serp/config.ru
pid: /var/www/serp/pids/thin.pid
group: root
timeout: 5
log: /var/www/serp/log/thin.log
max_conns: 1024
max_persistent_conns: 512
environment: staging
servers: 3
daemonize: true
user: root
chdir: /var/www/serp/
socket: /tmp/thin.sock
